export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const CHECK_AUTH_TIMEOUT = 'CHECK_AUTH_TIMEOUT';

export const GETTING_CATEGORIES = 'GETTING_CATEGORIES';
export const SET_CATEGORIES = 'SET_CATEGORIES';

export const GETTING_PRODUCTS = 'GETTING_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';

export const ORDER_START = 'ORDER_START';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';
export const ORDER_RESET = 'ORDER_RESET';

export const FETCHING_ORDERS = 'FETCHING_ORDERS';
export const SET_ORDERS = 'SET_ORDERS';
export const DELETE_ORDER = 'DELETE_ORDER';
