export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GETTING_CATEGORIES = 'GETTING_CATEGORIES';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const GETTING_CATEGORY_ITEMS = 'GETTING_CATEGORY_ITEMS';
export const SET_CATEGORY_ITEMS = 'SET_CATEGORY_ITEMS';
